"""
DOCX (Word) CAM document generator using python-docx.
Produces a professional Credit Appraisal Memo in Word format
with styled headings, tables, color-coded risk flags, and footer.
"""

import os
import logging
from datetime import datetime
from typing import Dict

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from backend.core.formatting import format_currency_cr, format_percentage, format_ratio

logger = logging.getLogger(__name__)


def generate_docx(state: dict) -> str:
    """
    Generate a professional Word document for the Credit Appraisal Memo.

    Args:
        state: Complete pipeline state dict.

    Returns:
        Path to the generated .docx file.
    """
    doc = Document()
    f = state.get("extracted_financials", {})
    company_name = state.get("company_name", "Unknown Company")
    company_id = state.get("company_id", "unknown")

    # ── Title Page ────────────────────────────────────────────────────
    title = doc.add_heading("CREDIT APPRAISAL MEMO", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(company_name)
    run.bold = True
    run.font.size = Pt(18)

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(f"Date: {datetime.now().strftime('%d %B %Y')}\n").font.size = Pt(11)
    meta.add_run(f"CIN: {f.get('cin', 'N/A')}\n").font.size = Pt(11)

    # Decision badge
    decision = state.get("decision", "PENDING")
    decision_para = doc.add_paragraph()
    decision_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    badge = decision_para.add_run(f"  {decision}  ")
    badge.bold = True
    badge.font.size = Pt(16)
    if decision == "APPROVE":
        badge.font.color.rgb = RGBColor(0, 128, 0)
    elif decision == "REJECT":
        badge.font.color.rgb = RGBColor(200, 0, 0)
    else:
        badge.font.color.rgb = RGBColor(200, 150, 0)

    doc.add_page_break()

    # ── CAM Content ──────────────────────────────────────────────────
    cam_text = state.get("cam_text", "")
    sections = cam_text.split("\n")

    for line in sections:
        line = line.strip()
        if not line:
            continue

        # Detect section headings (numbered or markdown)
        if line.startswith("#") or (len(line) > 2 and line[0].isdigit() and line[1] == "."):
            clean_heading = line.lstrip("#").lstrip("0123456789.").strip()
            doc.add_heading(clean_heading, level=1)
        elif line.startswith("##"):
            doc.add_heading(line.lstrip("#").strip(), level=2)
        else:
            para = doc.add_paragraph(line)
            # Color-code risk flags
            if "[CRITICAL]" in line:
                for run in para.runs:
                    run.font.color.rgb = RGBColor(200, 0, 0)
                    run.bold = True
            elif "[HIGH]" in line:
                for run in para.runs:
                    run.font.color.rgb = RGBColor(230, 130, 0)

    # ── Financial Summary Table ──────────────────────────────────────
    doc.add_heading("Financial Summary", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Light Grid Accent 1"

    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = "Metric"
    hdr_cells[1].text = "Value"

    metrics = [
        ("Revenue", format_currency_cr(f.get("revenue_crore"))),
        ("EBITDA Margin", format_percentage(f.get("ebitda_margin_pct"))),
        ("PAT", format_currency_cr(f.get("pat_crore"))),
        ("DSCR", format_ratio(f.get("dscr"))),
        ("Current Ratio", format_ratio(f.get("current_ratio"))),
        ("Net Worth", format_currency_cr(f.get("net_worth_crore"))),
        ("Total Debt", format_currency_cr(f.get("total_debt_crore"))),
        ("Risk Score", f"{state.get('final_risk_score', 'N/A')}/100"),
        ("Risk Category", str(state.get("risk_category", "N/A"))),
        ("Recommended Limit", format_currency_cr(state.get("recommended_loan_limit_crore"))),
    ]

    for metric, value in metrics:
        row = table.add_row().cells
        row[0].text = metric
        row[1].text = value

    # ── Footer ────────────────────────────────────────────────────────
    doc.add_paragraph("")
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.add_run(
        f"Generated by Intelli-Credit AI | {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(128, 128, 128)

    # Save
    output_dir = os.path.join("uploads", company_id)
    os.makedirs(output_dir, exist_ok=True)
    safe_name = company_name.replace(" ", "_").replace("/", "_")[:50]
    output_path = os.path.join(output_dir, f"CAM_{safe_name}.docx")
    doc.save(output_path)

    logger.info(f"[DOCX] Saved to {output_path}")
    return output_path
