'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAnalysisStore } from '@/store/analysisStore';
import { getReportPdfUrlV1, getReportUrlV1, getResultsV1 } from '@/lib/api';
import CamPreview from '@/components/CamPreview';

export default function CamPage() {
  const [camText, setCamText] = useState('');
  const [docxReady, setDocxReady] = useState(false);
  const [pdfReady, setPdfReady] = useState(false);
  const [loading, setLoading] = useState(true);
  const { companyId, companyName, setResult } = useAnalysisStore();
  const router = useRouter();

  useEffect(() => {
    if (!companyId) return;
    getResultsV1(companyId)
      .then((res: any) => {
        setResult(res.data);
        setCamText(String(res.data?.explanation?.decision_narrative || ''));
        setDocxReady(Boolean(res.data?.cam_docx_path));
        setPdfReady(Boolean(res.data?.cam_pdf_path));
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [companyId, setResult]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-56px)] bg-ob-bg">
        <p className="text-ob-muted text-base animate-pulse">Loading CAM report...</p>
      </div>
    );
  }

  return (
    <div className="bg-ob-bg py-12 px-4 md:px-8">
      <div className="max-w-[860px] mx-auto">
        {/* Document shell */}
        <div className="bg-ob-glass border border-ob-edge rounded-[12px] backdrop-blur-[28px]">
          {/* Header strip */}
          <div className="bg-transparent px-8 py-5 border-b border-ob-edge rounded-t-[12px] flex flex-col md:flex-row md:items-center md:justify-between gap-3">
            <div>
              <p className="font-mono text-[9px] font-normal tracking-[0.14em] uppercase text-ob-dim">Credit Appraisal Memorandum</p>
              <p className="font-display text-[22px] text-ob-text mt-1">{companyName || 'Company'}</p>
            </div>
            <div className="flex flex-col items-end gap-1">
              <span className="font-mono text-[12px] text-ob-muted">REF-{companyId?.slice(0, 8)?.toUpperCase() || 'N/A'}</span>
              <span className="font-mono text-[12px] text-ob-muted">{new Date().toLocaleDateString()}</span>
              {docxReady && (
                <span className="inline-block px-2 py-0.5 bg-ob-glass2 text-ob-text text-[10px] uppercase tracking-wider font-medium rounded">Ready</span>
              )}
            </div>
          </div>

          {/* Document body */}
          <div className="px-8 py-6">
            {camText ? (
              <CamPreview camText={camText} />
            ) : (
              <p className="text-ob-muted text-[14px]">CAM text will appear once analysis is completed.</p>
            )}
          </div>

          {/* Document footer */}
          <div className="border-t border-ob-edge px-8 py-4 rounded-b-[12px] flex items-center justify-between">
            <p className="text-[12px] text-ob-muted">
              Generated by InsightCredit · {new Date().toLocaleDateString()}
            </p>
            <div className="flex gap-3 no-print">
              {docxReady && (
                <a
                  href={getReportUrlV1(companyId)}
                  className="px-[16px] py-[8px] bg-ob-text text-ob-bg rounded-[6px] text-[12px] font-body font-bold no-underline hover:bg-ob-cream transition-all"
                >
                  Download .docx
                </a>
              )}
              {pdfReady && (
                <a
                  href={getReportPdfUrlV1(companyId)}
                  className="px-[16px] py-[8px] bg-ob-glass2 border border-ob-edge text-ob-text rounded-[6px] text-[12px] font-body font-normal no-underline hover:bg-ob-glass hover:border-ob-edge2 transition-all"
                >
                  Download .pdf
                </a>
              )}
              <button
                onClick={() => window.print()}
                className="px-[16px] py-[8px] bg-transparent border border-ob-edge text-ob-muted rounded-[6px] text-[12px] font-body font-normal hover:text-ob-text hover:border-ob-edge2 transition-all"
              >
                Print
              </button>
            </div>
          </div>
        </div>

        {/* Chat CTA */}
        <div className="mt-5 text-center no-print">
          <button
            onClick={() => router.push('/app/chat')}
            className="px-[24px] py-[12px] bg-ob-text text-ob-bg font-body font-bold rounded-[6px] text-[13px] transition-all hover:bg-ob-cream"
          >
            Chat with CAM Report →
          </button>
        </div>
      </div>
    </div>
  );
}
