'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAnalysisStore } from '@/store/analysisStore';
import { getReportPdfUrlV1, getReportUrlV1, getResultsV1 } from '@/lib/api';
import CamPreview from '@/components/CamPreview';

export default function CamPage() {
  const [camText, setCamText] = useState('');
  const [docxReady, setDocxReady] = useState(false);
  const [pdfReady, setPdfReady] = useState(false);
  const [loading, setLoading] = useState(true);
  const { companyId, companyName } = useAnalysisStore();
  const router = useRouter();

  useEffect(() => {
    if (!companyId) return;
    getResultsV1(companyId)
      .then((res) => {
        setCamText(String(res.data?.explanation?.decision_narrative || ''));
        setDocxReady(Boolean(res.data?.cam_docx_path));
        setPdfReady(Boolean(res.data?.cam_pdf_path));
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [companyId]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-56px)] bg-ic-page">
        <p className="text-ic-muted text-base animate-pulse">Loading CAM report...</p>
      </div>
    );
  }

  return (
    <div className="bg-ic-page py-12 px-4 md:px-8">
      <div className="max-w-[860px] mx-auto">
        {/* Document shell */}
        <div className="bg-ic-surface border border-ic-border rounded-[12px] shadow-sm">
          {/* Header strip */}
          <div className="bg-ic-surface-mid px-8 py-5 border-b border-ic-border rounded-t-[12px] flex flex-col md:flex-row md:items-center md:justify-between gap-3">
            <div>
              <p className="text-[10px] font-medium tracking-[0.12em] uppercase text-ic-muted">Credit Appraisal Memorandum</p>
              <p className="font-display text-[22px] text-ic-text mt-1">{companyName || 'Company'}</p>
            </div>
            <div className="flex flex-col items-end gap-1">
              <span className="font-mono text-[12px] text-ic-muted">REF-{companyId?.slice(0, 8)?.toUpperCase() || 'N/A'}</span>
              <span className="font-mono text-[12px] text-ic-muted">{new Date().toLocaleDateString()}</span>
              {docxReady && (
                <span className="inline-block px-2 py-0.5 bg-ic-accent-light text-ic-accent text-[10px] uppercase tracking-wider font-medium rounded">Ready</span>
              )}
            </div>
          </div>

          {/* Document body */}
          <div className="px-8 py-6">
            {camText ? (
              <CamPreview camText={camText} />
            ) : (
              <p className="text-ic-muted text-[14px]">CAM text will appear once analysis is completed.</p>
            )}
          </div>

          {/* Document footer */}
          <div className="border-t border-ic-border px-8 py-4 rounded-b-[12px] flex items-center justify-between">
            <p className="text-[12px] text-ic-muted">
              Generated by InsightCredit · {new Date().toLocaleDateString()}
            </p>
            <div className="flex gap-3 no-print">
              {docxReady && (
                <a
                  href={getReportUrlV1(companyId)}
                  className="px-4 py-2 bg-ic-accent text-white rounded-[6px] text-[12px] font-medium no-underline hover:opacity-90 transition-opacity"
                >
                  Download .docx
                </a>
              )}
              {pdfReady && (
                <a
                  href={getReportPdfUrlV1(companyId)}
                  className="px-4 py-2 bg-ic-surface border border-ic-border text-ic-text rounded-[6px] text-[12px] font-medium no-underline hover:opacity-90 transition-opacity"
                >
                  Download .pdf
                </a>
              )}
              <button
                onClick={() => window.print()}
                className="px-4 py-2 bg-ic-surface-mid border border-ic-border text-ic-text rounded-[6px] text-[12px] font-medium hover:opacity-90 transition-opacity"
              >
                Print
              </button>
            </div>
          </div>
        </div>

        {/* Chat CTA */}
        <div className="mt-5 text-center no-print">
          <button
            onClick={() => router.push('/app/chat')}
            className="px-5 py-2.5 bg-ic-accent text-white font-medium rounded-[10px] text-[13px] transition-opacity hover:opacity-90"
          >
            Chat with CAM Report →
          </button>
        </div>
      </div>
    </div>
  );
}
